#!/bin/bash -e
#
# avmerge - Merge audio and video from two separate files
# usage: avmerge video.mp4 audio.mp3 [video-out.mp4]
#
# yaswant.pradhan 2016-07-28
# -----------------------------------------------------------------------------

command -v ffmpeg 1>/dev/null \
  || { echo "ffmpeg not found, but required to run ${0##*/}"; exit 1; }

if [[ $# -lt 2 ]]; then
  echo "usage: ${0##*/} video_in.mp4 audio_in.mp3 [video_out.mp4]"
  exit 2
fi
_outfile="${1%.*}-out.${1##*.}"
video_out=${3:-"$_outfile"}

ffmpeg -i "$1" -i "$2" -vcodec copy -acodec copy -shortest "$video_out"
