#!/bin/bash
# dec2bin decimal_value
#
# Convert Value from decimal to binary
# yaswant.pradhan

[[ $# -eq 0 ]] && echo "usage: $(basename $0) decimal_value" && exit 1
for i in $@; do
    bc <<< "obase=2;$i"
    # echo "obase=2;$i" |bc
done
