#!/bin/bash -e
# dirchgrp directory usrgrp usrid
#   update permission of a directory by changing usergroup
#
#
# Example: http://superuser.com/questions/19318/how-can-i-give-write-access-of-a-folder-to-all-users-in-linux
# To best share with multiple users who should be able to write in /var/www,
# it should be assigned a common group. For example the default group for web
# content on Ubuntu and Debian is www-data. Make sure all the users who need
# write access to /var/www are in this group.

[[ $# -ne 3 ]] && echo -e "Usage: ${0##*/} DIRECTORY USRGRP USRID" && exit 1

sudo usermod -a -G "$2" "$3"

# Then set the correct permissions on directory
sudo chgrp -R "$2" "$1"
sudo chmod -R g+w "$1"

# Additionally, you should make the directory and all directories below it
# "set GID", so that all new files and directories created under /var/www are
# owned by the www-data group:
sudo find "$1" -type d -exec chmod 2775 {} \;

# Find all files in $1 and add read and write permission for
# owner and group:
sudo find "$1" -type f -exec chmod ug+rw {} \;

# You might have to log out and log back in to be able to make changes if
# you're editing permission for your own account.
