#!/bin/bash
#
# Extract from an archive (optionally compressed) with full path
# yaswant.pradhan

which unrar &>/dev/null;
[[ $? -ne 0 ]] && export PATH=$PATH:'/home/h05/fra6/pkg/rar'

which 7z &>/dev/null;
[[ $? -ne 0 ]] && export PATH=$PATH:'/home/h05/fra6/pkg/p7zip_9.04/bin'


# Extract file/archive:
if [ -f $1 ] ; then
    case $1 in
        *.tar.bz2)      tar xvjf $1 ;;
        *.tar.gz)       tar xvzf $1 ;;
        *.bz2)          bunzip2 $1  ;;
        *.rar)          unrar x $1  ;;
        *.gz)           pigz -d $1  ;;    # gunzip $1   ;;
        *.tar)          tar xvf $1  ;;
        *.tbz2|*.tbz)   tar xvjf $1 ;;
        *.tgz)          tar xvzf $1 ;;
        *.zip)          unzip $1    ;;
        *.Z)            uncompress $1 ;;
        *.7z)           7z x $1     ;;
        *)              echo "extract: '$1' cannot be restored" ;;
    esac
else
    echo "extract: '$1' is not a valid file"
fi


