#!/bin/bash
# fqp filename(s)
# returns fully qualified path of files/directories
#
# 2015-12-11 yaswant.pradhan
# -----------------------------------------------------------------------------

[[ $# -eq 0 ]] && echo "usage: ${0##/*} filename(s)" && exit 1

case "$OSTYPE" in
  'linux'*)
    for i in "$@"; do readlink -ev "$i"; done
    ;;
  'darwin'*)
    for i in "$@"; do stat -f "$i"; done
    ;;
  *)
    echo "Error: Unsupported OS"; exit 1
    ;;
esac
