#!/bin/bash -e
#
# lsempty
#       List empty files/directories in a specific path
#
# Usage:
#       lsempty [path] [depth]
#
#       path: specific path (def: $PWD)
#       depth: search levels under path (def: 100)
#
# yaswant.pradhan
# 2019-03-15 osx and DEBUG mode support (yp)
# ----------------------------------------------------------------------------
[ -n "$DEBUG" ] && set -x

SP="${1:-$PWD}"
MD="${2:-100}"

[ -z $SP ] && SP=$PWD
cd $SP

echo -e "List of empty files/directories in $SP: \n"
case "$OSTYPE" in
  darwin*) find $SP -maxdepth $MD -empty -print | sort | nl -p;;
  linux*) find $SP -maxdepth $MD -empty -printf "%u %Y %p  ..%sb\n" | sort | nl -p;;
  *) echo 'OS not supported';;
esac

