#!/bin/bash
# Number of days between two dates.
#
# usage:
#   ndays DATE1 [DATE2]
#
# args:
#   DATE1   First date (usually YYYY-mm-dd form, but can accept other forms)
#   DATE2   Last date (default is Today)
#
# requires:
#   date2julian, gnu date
#
# yaswant.pradhan
# -----------------------------------------------------------------------------

command -v date2julian || { echo 'date2julian not found'; exit 1;}
case "$#" in
    1 ) DATE1=$(date -d "$1" +%F)
        DATE2=$(date +%F)
        ;;
    2 ) DATE1=$(date -d "$1" +%F)
        DATE2=$(date -d "$2" +%F)
        ;;
    * ) echo -e "syntax: $(basename $0) DATE1 [DATE2]"
        exit 2
        ;;
esac

jd1=$(date2julian $DATE1)
jd2=$(date2julian $DATE2)
echo $(( jd2 - jd1 ))
