#!/bin/bash
# num_days DATE1 [DATE2]
# yaswant.pradhan

case "$#" in
    1 ) DATE1=$(date -d $1 +%F)
        DATE2=$(date +%F)
        ;;
    2 ) DATE1=$(date -d $1 +%F)
        DATE2=$(date -d $2 +%F)
        ;;
    * ) echo -e "syntax: $(basename $0) DATE1 [DATE2]"
        exit 2
        ;;
esac

echo $(( (`date -d $DATE2 +%s` - `date -d $DATE1 +%s`) /(24*3600) ))

