#!/bin/bash
# Remove directory quickly
# yaswant.pradhan
# -----------------------------------------------------------------------------

[[ -e "$1" ]] || { echo "$1: No such directory"; exit 1; }
empty_dir=$(mktemp -d -t rmd-XXXXX)

# parse directory array from input arguments
mapfile -t dirs < <(printf "%s\n" "$@")

for dir in "${dirs[@]}"; do
  [ -f "$dir" ] && { echo "[WARNING] File not deleted: $dir"; continue; }
  if [ -d "$dir" ]; then
    printf "removing %s.. " "$dir"
    rsync -aq --delete "${empty_dir}/" "${dir}/" && rm -rf "$dir"
    printf "done.\n"
  else
    echo "[WARNING] $dir: No such directory"
  fi
done

#  clean-up tmp directory
rm -rf "$empty_dir"
